# github-handson

# 打ち込んだコードと結果
![image](https://github.com/Ema-Sakai/github-handson/assets/166620990/5ca7485c-c322-48a6-8205-5452d26e5315)
![image](https://github.com/Ema-Sakai/github-handson/assets/166620990/6fc9cc4a-3f17-444d-b778-2d5258d9dc11)
![image](https://github.com/Ema-Sakai/github-handson/assets/166620990/38c7314a-1d9d-4d59-937a-d0b079075768)
![image](https://github.com/Ema-Sakai/github-handson/assets/166620990/8e46bf0c-044d-45dd-be40-8f2a3b185a7f)

無事、READMEの作成に成功した！

## 2024/04/24追記
README作成後（4/19）、「打ち込んだコードと結果」の画像を添付したらアカウントが一時凍結となった。  
その後運営にアカウント復活の申し立てをし、4月24日にようやく解除された。  
今回なぜ垢バンされたのか、トリガーについて運営に確認中。
もし返答をもらえたら、それについてさらに追記したい。

## 2024/04/27追記
4/24に追記後の午前0時過ぎに、またしても垢バンされた。  
原因含め運営に問い合わせたところ、  
「We've investigated this issue and found the root cause to be an error in how malicious behavior was flagged, causing the suspension of some accounts. This error has been resolved and the affected accounts have been reinstated.」と返答が。  
ざっくり訳すと、「垢バン対象者を検知する仕組みが一時的におかしかった」らしいです。  
なんにせよアカウントが戻ってきてほっとした～！
